
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftOPTASUOPHIKUleftOPKAKENUMBER OPHIKU OPKAKE OPTASU RETURN SEMI\n    teigi : RETURN expression SEMI\n    \n    expression : NUMBER\n               | expression OPTASU expression\n               | expression OPHIKU expression\n               | expression OPKAKE expression\n    '
    
_lr_action_items = {'RETURN':([0,],[2,]),'$end':([1,5,],[0,-1,]),'NUMBER':([2,6,7,8,],[4,4,4,4,]),'SEMI':([3,4,9,10,11,],[5,-2,-3,-4,-5,]),'OPTASU':([3,4,9,10,11,],[6,-2,-3,-4,-5,]),'OPHIKU':([3,4,9,10,11,],[7,-2,-3,-4,-5,]),'OPKAKE':([3,4,9,10,11,],[8,-2,8,8,-5,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'teigi':([0,],[1,]),'expression':([2,6,7,8,],[3,9,10,11,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> teigi","S'",1,None,None,None),
  ('teigi -> RETURN expression SEMI','teigi',3,'p_top','compile.py',17),
  ('expression -> NUMBER','expression',1,'p_expression','compile.py',25),
  ('expression -> expression OPTASU expression','expression',3,'p_expression','compile.py',26),
  ('expression -> expression OPHIKU expression','expression',3,'p_expression','compile.py',27),
  ('expression -> expression OPKAKE expression','expression',3,'p_expression','compile.py',28),
]
