
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftOPTASUOPHIKUleftOPKAKEOPWARUCOMPEQ EQUALS IF KAKKO KOKKA LBRACE NUMBER OPHIKU OPKAKE OPTASU OPWARU RBRACE RETURN SEMI SYMBOL TYPE\n    teigi : kansuuteigi\n          | teigi kansuuteigi\n    \n    kansuuteigi : TYPE SYMBOL KAKKO KOKKA LBRACE bunlist RBRACE\n    \n    kansuuteigi : TYPE SYMBOL KAKKO TYPE SYMBOL KOKKA LBRACE bunlist RBRACE\n    \n    bunlist : bun\n            | bunlist bun\n    \n    bun : RETURN expression SEMI\n    \n    bun : TYPE SYMBOL SEMI\n    \n    bun : SYMBOL EQUALS expression SEMI\n    \n    bun : IF KAKKO expression COMPEQ expression KOKKA LBRACE bunlist RBRACE\n    \n    bun : expression SEMI\n    \n    expression : NUMBER\n               | expression OPTASU expression\n               | expression OPHIKU expression\n               | expression OPKAKE expression\n               | expression OPWARU expression\n    \n    expression : SYMBOL \n    \n    expression : SYMBOL KAKKO KOKKA\n    \n    expression : SYMBOL KAKKO expression KOKKA\n    '
    
_lr_action_items = {'TYPE':([0,1,2,4,6,10,14,15,20,24,25,28,34,35,39,45,46,51,52,53,],[3,3,-1,-2,7,12,12,-5,12,-3,-6,-11,12,-8,-7,-4,-9,12,12,-10,]),'$end':([1,2,4,24,45,],[0,-1,-2,-3,-4,]),'SYMBOL':([3,7,10,12,14,15,16,20,22,23,25,28,29,30,31,32,33,34,35,39,46,48,51,52,53,],[5,9,13,21,13,-5,27,13,27,27,-6,-11,27,27,27,27,27,13,-8,-7,-9,27,13,13,-10,]),'KAKKO':([5,13,18,27,],[6,23,33,23,]),'KOKKA':([6,9,19,23,27,37,38,40,41,42,43,47,49,],[8,11,-12,37,-17,-18,47,-13,-14,-15,-16,-19,50,]),'LBRACE':([8,11,50,],[10,20,51,]),'RETURN':([10,14,15,20,25,28,34,35,39,46,51,52,53,],[16,16,-5,16,-6,-11,16,-8,-7,-9,16,16,-10,]),'IF':([10,14,15,20,25,28,34,35,39,46,51,52,53,],[18,18,-5,18,-6,-11,18,-8,-7,-9,18,18,-10,]),'NUMBER':([10,14,15,16,20,22,23,25,28,29,30,31,32,33,34,35,39,46,48,51,52,53,],[19,19,-5,19,19,19,19,-6,-11,19,19,19,19,19,19,-8,-7,-9,19,19,19,-10,]),'EQUALS':([13,],[22,]),'SEMI':([13,17,19,21,26,27,36,37,40,41,42,43,47,],[-17,28,-12,35,39,-17,46,-18,-13,-14,-15,-16,-19,]),'OPTASU':([13,17,19,26,27,36,37,38,40,41,42,43,44,47,49,],[-17,29,-12,29,-17,29,-18,29,-13,-14,-15,-16,29,-19,29,]),'OPHIKU':([13,17,19,26,27,36,37,38,40,41,42,43,44,47,49,],[-17,30,-12,30,-17,30,-18,30,-13,-14,-15,-16,30,-19,30,]),'OPKAKE':([13,17,19,26,27,36,37,38,40,41,42,43,44,47,49,],[-17,31,-12,31,-17,31,-18,31,31,31,-15,-16,31,-19,31,]),'OPWARU':([13,17,19,26,27,36,37,38,40,41,42,43,44,47,49,],[-17,32,-12,32,-17,32,-18,32,32,32,-15,-16,32,-19,32,]),'RBRACE':([14,15,25,28,34,35,39,46,52,53,],[24,-5,-6,-11,45,-8,-7,-9,53,-10,]),'COMPEQ':([19,27,37,40,41,42,43,44,47,],[-12,-17,-18,-13,-14,-15,-16,48,-19,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'teigi':([0,],[1,]),'kansuuteigi':([0,1,],[2,4,]),'bunlist':([10,20,51,],[14,34,52,]),'bun':([10,14,20,34,51,52,],[15,25,15,25,15,25,]),'expression':([10,14,16,20,22,23,29,30,31,32,33,34,48,51,52,],[17,17,26,17,36,38,40,41,42,43,44,17,49,17,17,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> teigi","S'",1,None,None,None),
  ('teigi -> kansuuteigi','teigi',1,'p_top','compile.py',19),
  ('teigi -> teigi kansuuteigi','teigi',2,'p_top','compile.py',20),
  ('kansuuteigi -> TYPE SYMBOL KAKKO KOKKA LBRACE bunlist RBRACE','kansuuteigi',7,'p_kansuuteigi','compile.py',33),
  ('kansuuteigi -> TYPE SYMBOL KAKKO TYPE SYMBOL KOKKA LBRACE bunlist RBRACE','kansuuteigi',9,'p_kansuuteigi_hiki','compile.py',40),
  ('bunlist -> bun','bunlist',1,'p_bunlist','compile.py',47),
  ('bunlist -> bunlist bun','bunlist',2,'p_bunlist','compile.py',48),
  ('bun -> RETURN expression SEMI','bun',3,'p_bun_return','compile.py',59),
  ('bun -> TYPE SYMBOL SEMI','bun',3,'p_bun_sengen','compile.py',66),
  ('bun -> SYMBOL EQUALS expression SEMI','bun',4,'p_bun_dainyu','compile.py',73),
  ('bun -> IF KAKKO expression COMPEQ expression KOKKA LBRACE bunlist RBRACE','bun',9,'p_bun_if','compile.py',79),
  ('bun -> expression SEMI','bun',2,'p_bun_expression_only','compile.py',85),
  ('expression -> NUMBER','expression',1,'p_expression','compile.py',98),
  ('expression -> expression OPTASU expression','expression',3,'p_expression','compile.py',99),
  ('expression -> expression OPHIKU expression','expression',3,'p_expression','compile.py',100),
  ('expression -> expression OPKAKE expression','expression',3,'p_expression','compile.py',101),
  ('expression -> expression OPWARU expression','expression',3,'p_expression','compile.py',102),
  ('expression -> SYMBOL','expression',1,'p_expression_var','compile.py',113),
  ('expression -> SYMBOL KAKKO KOKKA','expression',3,'p_expression_funccall','compile.py',119),
  ('expression -> SYMBOL KAKKO expression KOKKA','expression',4,'p_expression_funcall_hiki','compile.py',125),
]
