
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftOPTASUOPHIKUleftOPKAKEEQUALS KAKKO KOKKA LBRACE NUMBER OPHIKU OPKAKE OPTASU RBRACE RETURN SEMI SYMBOL TYPE\n    teigi : kansuuteigi\n    \n    kansuuteigi : TYPE SYMBOL KAKKO KOKKA LBRACE bunlist RBRACE\n    \n    bunlist : bun\n            | bunlist bun\n    \n    bun : RETURN expression SEMI\n    \n    bun : TYPE SYMBOL SEMI\n    \n    bun : SYMBOL EQUALS expression SEMI\n    \n    expression : NUMBER\n               | expression OPTASU expression\n               | expression OPHIKU expression\n               | expression OPKAKE expression\n    \n    expression : SYMBOL\n    '
    
_lr_action_items = {'TYPE':([0,7,10,11,16,20,22,26,],[3,8,8,-3,-4,-6,-5,-7,]),'$end':([1,2,15,],[0,-1,-2,]),'SYMBOL':([3,7,8,10,11,12,14,16,20,22,23,24,25,26,],[4,9,13,9,-3,19,19,-4,-6,-5,19,19,19,-7,]),'KAKKO':([4,],[5,]),'KOKKA':([5,],[6,]),'LBRACE':([6,],[7,]),'RETURN':([7,10,11,16,20,22,26,],[12,12,-3,-4,-6,-5,-7,]),'EQUALS':([9,],[14,]),'RBRACE':([10,11,16,20,22,26,],[15,-3,-4,-6,-5,-7,]),'NUMBER':([12,14,23,24,25,],[18,18,18,18,18,]),'SEMI':([13,17,18,19,21,27,28,29,],[20,22,-8,-12,26,-9,-10,-11,]),'OPTASU':([17,18,19,21,27,28,29,],[23,-8,-12,23,-9,-10,-11,]),'OPHIKU':([17,18,19,21,27,28,29,],[24,-8,-12,24,-9,-10,-11,]),'OPKAKE':([17,18,19,21,27,28,29,],[25,-8,-12,25,25,25,-11,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'teigi':([0,],[1,]),'kansuuteigi':([0,],[2,]),'bunlist':([7,],[10,]),'bun':([7,10,],[11,16,]),'expression':([12,14,23,24,25,],[17,21,27,28,29,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> teigi","S'",1,None,None,None),
  ('teigi -> kansuuteigi','teigi',1,'p_top','compile.py',17),
  ('kansuuteigi -> TYPE SYMBOL KAKKO KOKKA LBRACE bunlist RBRACE','kansuuteigi',7,'p_kansuuteigi','compile.py',24),
  ('bunlist -> bun','bunlist',1,'p_bunlist','compile.py',31),
  ('bunlist -> bunlist bun','bunlist',2,'p_bunlist','compile.py',32),
  ('bun -> RETURN expression SEMI','bun',3,'p_bun_return','compile.py',43),
  ('bun -> TYPE SYMBOL SEMI','bun',3,'p_bun_sengen','compile.py',50),
  ('bun -> SYMBOL EQUALS expression SEMI','bun',4,'p_bun_dainyu','compile.py',57),
  ('expression -> NUMBER','expression',1,'p_expression','compile.py',63),
  ('expression -> expression OPTASU expression','expression',3,'p_expression','compile.py',64),
  ('expression -> expression OPHIKU expression','expression',3,'p_expression','compile.py',65),
  ('expression -> expression OPKAKE expression','expression',3,'p_expression','compile.py',66),
  ('expression -> SYMBOL','expression',1,'p_expression_var','compile.py',78),
]
