
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftOPTASUOPHIKUleftOPKAKECOMPEQ EQUALS IF KAKKO KOKKA LBRACE NUMBER OPHIKU OPKAKE OPTASU RBRACE RETURN SEMI SYMBOL TYPE\n    teigi : kansuuteigi\n          | teigi kansuuteigi\n    \n    kansuuteigi : TYPE SYMBOL KAKKO KOKKA LBRACE bunlist RBRACE\n    \n    kansuuteigi : TYPE SYMBOL KAKKO TYPE SYMBOL KOKKA LBRACE bunlist RBRACE\n    \n    bunlist : bun\n            | bunlist bun\n    \n    bun : RETURN expression SEMI\n    \n    bun : TYPE SYMBOL SEMI\n    \n    bun : SYMBOL EQUALS expression SEMI\n    \n    bun : expression SEMI\n    \n    bun : IF KAKKO expression COMPEQ expression KOKKA LBRACE bunlist RBRACE\n    \n    expression : NUMBER\n               | expression OPTASU expression\n               | expression OPHIKU expression\n               | expression OPKAKE expression\n    \n    expression : SYMBOL\n    \n    expression : SYMBOL KAKKO KOKKA\n    \n    expression : SYMBOL KAKKO expression KOKKA\n    '
    
_lr_action_items = {'TYPE':([0,1,2,4,6,10,14,15,20,24,25,28,33,34,38,43,44,49,50,51,],[3,3,-1,-2,7,12,12,-5,12,-3,-6,-10,12,-8,-7,-4,-9,12,12,-11,]),'$end':([1,2,4,24,43,],[0,-1,-2,-3,-4,]),'SYMBOL':([3,7,10,12,14,15,16,20,22,23,25,28,29,30,31,32,33,34,38,44,46,49,50,51,],[5,9,13,21,13,-5,27,13,27,27,-6,-10,27,27,27,27,13,-8,-7,-9,27,13,13,-11,]),'KAKKO':([5,13,18,27,],[6,23,32,23,]),'KOKKA':([6,9,19,23,27,36,37,39,40,41,45,47,],[8,11,-12,36,-16,-17,45,-13,-14,-15,-18,48,]),'LBRACE':([8,11,48,],[10,20,49,]),'RETURN':([10,14,15,20,25,28,33,34,38,44,49,50,51,],[16,16,-5,16,-6,-10,16,-8,-7,-9,16,16,-11,]),'IF':([10,14,15,20,25,28,33,34,38,44,49,50,51,],[18,18,-5,18,-6,-10,18,-8,-7,-9,18,18,-11,]),'NUMBER':([10,14,15,16,20,22,23,25,28,29,30,31,32,33,34,38,44,46,49,50,51,],[19,19,-5,19,19,19,19,-6,-10,19,19,19,19,19,-8,-7,-9,19,19,19,-11,]),'EQUALS':([13,],[22,]),'SEMI':([13,17,19,21,26,27,35,36,39,40,41,45,],[-16,28,-12,34,38,-16,44,-17,-13,-14,-15,-18,]),'OPTASU':([13,17,19,26,27,35,36,37,39,40,41,42,45,47,],[-16,29,-12,29,-16,29,-17,29,-13,-14,-15,29,-18,29,]),'OPHIKU':([13,17,19,26,27,35,36,37,39,40,41,42,45,47,],[-16,30,-12,30,-16,30,-17,30,-13,-14,-15,30,-18,30,]),'OPKAKE':([13,17,19,26,27,35,36,37,39,40,41,42,45,47,],[-16,31,-12,31,-16,31,-17,31,31,31,-15,31,-18,31,]),'RBRACE':([14,15,25,28,33,34,38,44,50,51,],[24,-5,-6,-10,43,-8,-7,-9,51,-11,]),'COMPEQ':([19,27,36,39,40,41,42,45,],[-12,-16,-17,-13,-14,-15,46,-18,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'teigi':([0,],[1,]),'kansuuteigi':([0,1,],[2,4,]),'bunlist':([10,20,49,],[14,33,50,]),'bun':([10,14,20,33,49,50,],[15,25,15,25,15,25,]),'expression':([10,14,16,20,22,23,29,30,31,32,33,46,49,50,],[17,17,26,17,35,37,39,40,41,42,17,47,17,17,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> teigi","S'",1,None,None,None),
  ('teigi -> kansuuteigi','teigi',1,'p_top','compile.py',19),
  ('teigi -> teigi kansuuteigi','teigi',2,'p_top','compile.py',20),
  ('kansuuteigi -> TYPE SYMBOL KAKKO KOKKA LBRACE bunlist RBRACE','kansuuteigi',7,'p_kansuuteigi','compile.py',33),
  ('kansuuteigi -> TYPE SYMBOL KAKKO TYPE SYMBOL KOKKA LBRACE bunlist RBRACE','kansuuteigi',9,'p_kansuuteigi_1','compile.py',40),
  ('bunlist -> bun','bunlist',1,'p_bunlist','compile.py',47),
  ('bunlist -> bunlist bun','bunlist',2,'p_bunlist','compile.py',48),
  ('bun -> RETURN expression SEMI','bun',3,'p_bun_return','compile.py',59),
  ('bun -> TYPE SYMBOL SEMI','bun',3,'p_bun_sengen','compile.py',66),
  ('bun -> SYMBOL EQUALS expression SEMI','bun',4,'p_bun_dainyu','compile.py',73),
  ('bun -> expression SEMI','bun',2,'p_bun_expression_only','compile.py',79),
  ('bun -> IF KAKKO expression COMPEQ expression KOKKA LBRACE bunlist RBRACE','bun',9,'p_bun_if_then_only','compile.py',85),
  ('expression -> NUMBER','expression',1,'p_expression','compile.py',97),
  ('expression -> expression OPTASU expression','expression',3,'p_expression','compile.py',98),
  ('expression -> expression OPHIKU expression','expression',3,'p_expression','compile.py',99),
  ('expression -> expression OPKAKE expression','expression',3,'p_expression','compile.py',100),
  ('expression -> SYMBOL','expression',1,'p_expression_var','compile.py',111),
  ('expression -> SYMBOL KAKKO KOKKA','expression',3,'p_expression_funccall','compile.py',117),
  ('expression -> SYMBOL KAKKO expression KOKKA','expression',4,'p_expression_funccall_2','compile.py',123),
]
