#ifndef EXTCONF_H
#define EXTCONF_H
#define HAVE_OPENSSL_SSL_H 1
#define HAVE_RAND_EGD 1
#define HAVE_ENGINE_LOAD_DYNAMIC 1
#define HAVE_ENGINE_LOAD_CRYPTODEV 1
#define HAVE_EC_CURVE_NIST2NID 1
#define HAVE_X509_REVOKED_DUP 1
#define HAVE_X509_STORE_CTX_GET0_STORE 1
#define HAVE_SSL_CTX_SET_ALPN_SELECT_CB 1
#define HAVE_SSL_CTX_SET1_CURVES_LIST 1
#define HAVE_SSL_CTX_SET_ECDH_AUTO 1
#define HAVE_SSL_GET_SERVER_TMP_KEY 1
#define HAVE_SSL_IS_SERVER 1
#define HAVE_SSL_CTX 1
#define HAVE_ST_CTX 1
#define HAVE_CRYPTO_LOCK 1
#define HAVE_SSL_CTX_SET_TMP_ECDH_CALLBACK 1
#define HAVE_TS_RESP_CTX_SET_TIME_CB 1
#endif
