#define ABS_SRCDIR "/home/ec2-user/.rvm/src/ruby-3.0.6"
#define BUILDDIR   "/home/ec2-user/.rvm/src/ruby-3.0.6"
#define LIBPATHENV "LD_LIBRARY_PATH"
#define PRELOADENV "LD_PRELOAD"
#define PATH_SEPARATOR ":"
#define PATH_SEP   ':'
#define EXTOUT     ".ext"
#define ARCH       "x86_64-linux"
#define SOEXT      "so"
